rom-rb/rom-factory

lib/rom/factory/attributes/association.rb, lib/rom/factory/attributes/callable.rb, lib/rom/factory/attributes/regular.rb, lib/rom/factory/attributes/sequence.rb, lib/rom/factory/builder.rb, lib/rom/factory/dsl.rb, lib/rom/factory/factories.rb, spec/integration/rom/factory_spec.rb, spec/unit/rom/builder_spec.rb
This is a refactor which changes the way attributes are handled. We're no longer using a schema represented by `{ name => attr_object }`, instead we simply have an array with attributes. They have explicit names and encapsulate behavior. On top of this, `Associations::*` attribute types were added, and previous implementation of `belongs_to` support was refactored to use this. It means that we can now easily add remaining associations.
=> Refactor attribute and association handling

lib/rom/factory/attribute_registry.rb, lib/rom/factory/attributes/association.rb, lib/rom/factory/attributes/callable.rb, lib/rom/factory/attributes/regular.rb, lib/rom/factory/attributes/sequence.rb, lib/rom/factory/builder.rb, lib/rom/factory/dsl.rb, spec/spec_helper.rb, spec/unit/rom/attribute_registry_spec.rb, spec/unit/rom/builder_spec.rb
This adds `AttributeRegistry` which can be tsorted based on attribute dependencies, which allows syntax like this:
``` ruby
Factory.define(:user) do |f|
f.name "Jane"
f.email { |name| "#{name.downcase}@rom-rb.org" }
end
```
Associations will use this too, but that's another PR.
=> Dependant attributes

lib/rom/factory/attribute_registry.rb, lib/rom/factory/attributes/association.rb, lib/rom/factory/attributes/callable.rb, lib/rom/factory/attributes/regular.rb, lib/rom/factory/attributes/sequence.rb, lib/rom/factory/builder.rb, lib/rom/factory/dsl.rb, lib/rom/factory/factories.rb, spec/integration/rom/factory_spec.rb, spec/unit/rom/builder_spec.rb
This adds support for `has_many` and `has_one`. I ended up **not** using dependent attributes as it's a bit more complex, since we need to postpone persisting child tuples until parent is persisted.
=> Support for has_many and has_one associations

lib/rom/factory.rb, lib/rom/factory/builder.rb, lib/rom/factory/dsl.rb, lib/rom/factory/factories.rb, lib/rom/factory/sequences.rb, lib/rom/factory/tuple_evaluator.rb, spec/integration/rom/factory_spec.rb, spec/spec_helper.rb, spec/unit/rom/factory/builder_spec.rb
This adds support for setting custom struct namespace
``` ruby
my_factory = ROM::Factory.configure do { |c| c.rom = my_rom_container }
my_factory.struct_namespace(MyApp::Entities)[:user]
my_factory.structs.struct_namespace(MyApp::Entities)[:user]
my_factory.struct_namespace(MyApp::Entities).structs[:user]
```
=> Struct namespace support

lib/rom/factory/constants.rb, lib/rom/factory/factories.rb, lib/rom/factory/registry.rb, spec/integration/rom/factory_spec.rb
Solves #3 
@solnic I went with the option of creating this `Registry` to avoid having to raise the same error in multiple places. Maybe it is a little over kill we can always return to raising the exception in the two places that we access the registry.
=> Raise an exception when trying to access a factory that hasn't been defined

lib/rom/factory/attributes/callable.rb, spec/integration/rom/factory_spec.rb
Hello! I have some attributes in my factory that depend on other attributes:
```
Factory.define(:user) do |f|
f.first_name { fake(:name) }
f.last_name { fake(:name) }
f.email { |last_name| "#{last_name}@gmail.com" }
f.timestamps
end
```
For some reason I have to overwrite `last_name` and still get correct `email`:
```
Factory[:user, last_name: 'OtherLastName']
```
But I get `@gmail.com` instead of `OtherLastName@gmail.com`. Here is a fix for it.
=> Fix overwriting values of attrs with dependant attrs

lib/rom/factory/builder/persistable.rb, spec/integration/rom/factory_spec.rb
Before this change, persisted factories would crash if created with >1 trait and one of those traits included an association.
=> Fix use of multiple traits for persisted factories with associations

Gemfile
Apparently there needs to be a dependency on dry-core
I think is due to this changes https://github.com/rom-rb/rom/compare/v4.2.0...v4.2.1#diff-ec61118d3903feae5e618d34f8a1d6e9R12
=> Attempt to fix ci

lib/rom/factory/attributes/association.rb, lib/rom/factory/builder.rb, lib/rom/factory/tuple_evaluator.rb, spec/integration/rom/factory_spec.rb
This is a follow up to https://github.com/rom-rb/rom-factory/pull/30
Previously, building a many-to-one (`belongs_to`) record would persist the record to the DB. This patch addresses that issue by ensuring the `persist: false` option is honored in `ManyToOne` relationships.
=> Do not persist many-to-one child records when building a struct

.travis.yml
This ~(experimental)~ PR is about getting the build to green.
- Update CI matrix versions and add Ruby 2.6.1
- Update Bundler
- Also: Drop removed Travis directive `sudo: false`.
- Also: Drop the `script` directive, which does the default thing, already (run the `default` Rake task)
Q: Is the repo being built at: https://travis-ci.org/rom-rb/rom-factory/pull_requests
A: It is _now_.
=> Travis: Bump patch versions of matrix, update Bundler

lib/rom/factory/builder/persistable.rb, lib/rom/factory/constants.rb, spec/integration/rom/factory_spec.rb
I always typo some attribute name when using a factory. `rom-factory` ignores these typos. This PR makes `rom-factory` raise an error instead of the currently "ignore all the things" functionality. 
I am not sure if this is the best way to solve this problem but "it works" 🤷‍♂
=> Raise error when trying to set missing attribute

lib/rom/factory/builder.rb, spec/integration/rom/factory_spec.rb
This PR supports building structs when associated factories do not define parent associations.
```ruby
factory(:parent) do |f|
f.association(:child)
end
factory(:child) do |f|
end
factories[:parent] #=> Works!
factories.structs[:parent] #=> UnknownAttributeErrror :parent when structing the child
factories[:parent] #=> Works!
factories.structs[:parent] #=> Works!
```
=> Support building structs when associated factories do not define parent associations

lib/rom/factory/tuple_evaluator.rb, spec/integration/rom/factory_spec.rb, spec/shared/relations.rb
Prior to this, using a non-standard output schema that doesn't reject keys that are not present in the schema (as in `rom-http`), and with no PK defined on the schema, the `TupleEvaluator#struct_attrs` method would try to add a sequence value under the PK name, as `#primary_key` evaluated to `nil`, the attribute added looked like `"nil=>{n}"`, and the following error would occur (with rom-http output schema):
```
NoMethodError:
undefined method `to_sym' for nil:NilClass
```
The attribute was added in all cases where no PK was present, but was only noticeable when the output schema didn't reject keys that weren't defined in the schema.
=> Fix TupleEvaluator#struct_attrs for non-standard output schema

lib/rom/factory/attributes/association.rb, lib/rom/factory/dsl.rb, spec/integration/rom/factory_spec.rb
Previously, `rom-factory` ignored the `count` param of an association. This can lead to unexpected behavior, and potentially create records which a user would not expect to exist.
This PR makes it so if `count: 0` is specified on a `OneToOne` relationship, `rom-factory` will not create or build an associated record.
=> Honor zero count on one-to-one associations

lib/rom/factory/builder.rb, lib/rom/factory/dsl.rb, lib/rom/factory/factories.rb, spec/integration/rom/factory_spec.rb, spec/shared/relations.rb, spec/unit/rom/factory/builder_spec.rb
added the ability to pass the struct_namespace parameter to builder so you can create different builders with different struct namespaces within one factory
=> add struct_namespace option to builders

lib/rom/factory/attributes/association.rb, lib/rom/factory/tuple_evaluator.rb, spec/integration/rom/factory_spec.rb, spec/shared/relations.rb
This PR makes it possible to have `OneToOneThrough` in factories. This is incredibly important since oftentimes, one-to-one-throughs are critical when refactoring coupled relations in a codebase. 
I cannot get `factories.struct(:user)` to work with this. There is some strange stuff happening where the schema inferencing from the model expects a `user_id` on `addresses`, despite it being a `has_one`. I don't know how to resolve that. I believe there is some strange schema merging going on, but I do not have enough context to debug it. @solnic can someone help me with this? 
<details>
<summary><b>Click here to show the backtrace</b></summary>
<pre>
1) ROM::Factory.structs one-to-one-through when building a struct persists the relation properly without pre-existing assoc record …
=> Add support for one-to-one-though associations

docsite/source/index.html.md
Hey, I found the issue in the documentation:
```
(rdb:1) Factory.structs[:payment, id: 3]
#<ROM::Struct::Payment id=3 ...>
(rdb:1) Factory.structs(:payment, id: 3)
/Users/anton/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/debug.rb:286:in `eval':wrong number of arguments (given 2, expected 0)
```
=> Fix wrong information about building memory object

lib/rom/factory/dsl.rb
Naive benchmark
```ruby
require 'faker'
require 'dry/core/cache'
require 'dry/core/inflector'
require 'benchmark/ips'
class Context
extend ::Dry::Core::Cache
def get_faker_constant_cache(type)
fetch_or_store(:faker, type) do
::Faker.const_get(::Dry::Core::Inflector.classify(type.to_s))
end
end
def get_faker_constant(type)
::Faker.const_get(::Dry::Core::Inflector.classify(type.to_s))
end
end
context = Context.new
Benchmark.ips do |x|
x.report('cached') do
context.get_faker_constant_cache(:lorem)
end
x.report('non-cached') do
context.get_faker_constant(:lorem)
end
x.compare!
end
```
Results
```
Warming up --------------------------------------
cached   189.223k i/100ms
non-cached     4.880k i/100ms
Calculating -------------------------------------
cached      1.885M (± 3.0%) i/s - …
```
=> Cache faker constants

lib/rom/factory/dsl.rb, spec/integration/rom/factory_spec.rb, spec/shared/relations.rb
`classify` singularizes the input. `camelize` doesn't. Before that change `f.alias { fake(:greek_philosophers, :name) }` raised an exception.
Thanks and best regards
=> Expose plural faker generators like "Faker::GreekPhilosophers" properly

lib/rom/factory/sequences.rb
Without this change potential incrementation can "go away" and can actually mismatch by 1 if run in multiple threads the same time. This can lead to super weird errors where counter is not as expected (been there, took me ages to debug).
ref: https://github.com/ruby-concurrency/concurrent-ruby/issues/970
=> Make registry fully thread safe

Gemfile
I had errors from `pry` while booting until I let it use the latest version.
=> Remove version restriction from `pry` in `Gemfile`

Gemfile
With `~> 0.21` I can't bundle on my machine but when I update it I can.
=> Update `pg` gem in `Gemfile`

lib/rom/factory/attribute_registry.rb, lib/rom/factory/attributes/association.rb, lib/rom/factory/builder.rb, lib/rom/factory/builder/persistable.rb, lib/rom/factory/dsl.rb, lib/rom/factory/tuple_evaluator.rb, spec/integration/rom/factory_spec.rb, spec/shared/relations.rb, spec/spec_helper.rb
This adds support for building associated structs in case of `ManyToMany` and `OneToOneThrough` association types, where intermediate join tables are involved. It works with persistable and in-memory structs.
```ruby
factories.define(:user) do |f|
f.first_name { fake(:name, :first_name) }
f.last_name { fake(:name, :last_name) }
f.email { fake(:internet, :email) }
f.timestamps
f.association :address
end
factories.define(:user_address) do |f|
f.association(:user)
f.association(:address)
f.timestamps
end
factories.define(:address) do |f|
f.full_address { fake(:address, :full_address) }
end
factories[:user]
factories.structs[:user]
#<ROM::Struct::User id=1 last_name="Zieme" first_name="Mallory" alias=nil email="lu_nolan@hermiston-hansen.example" created_at=2023-11-24 10:20:05.920642677 +0000 …
```
=> Introduce ManyToMany and OneToOneThrough builder

lib/rom/factory/tuple_evaluator.rb, spec/integration/rom/factory_spec.rb
It turned out it's not always possible to use the passed value in a block. Passing values requires more attention, there are open issues about it, but it's a nice improvement anyway
=> Fix using passed values in callable attributes

Gemfile, docsite/source/index.html.md, lib/rom/factory/factories.rb, spec/integration/rom/factory_spec.rb, spec/shared/database.rb
This adds two methods to the `Factories` instances:
* `Factory.create` as an alias of `Factory.[]`
* `Factory.build` as a delgator to `Factory.structs#[]`
These are more commonly expected methods for interacting with a Factory, 
and are slightly more expressive when encountering thier usage.
ref: https://discourse.hanamirb.org/t/hanami-hack-day-at-rubyconf-2024/1051
This also closes a connection leak when running the test suite.
=> Add `Factory.build` and `Factory.create`

lib/rom/factory/dsl.rb
Traits can currently be specified as the second argument when calling
`association`:
```ruby
Factory.define :category do |category|
category.association :image, :fancy 
end
```
This change will add support for specifying `traits:` as an option:
```ruby
Factory.define :category do |category|
category.association :image, traits: [:fancy]
end
```
=> Add support for named `traits` arg with `association`
